# Auto-provision Prometheus as datasource for Grafana
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '5s'

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    jsonData:
      version: Flux
      organization: owner
      defaultBucket: eews
    secureJsonData:
      token: eFWu0UGcCzvGAX1w-z43heHjfDk8swujfryImhIsTrAkNJOgfMRSYsgYVki-QTiWHDwKLJtxsSnCmHhxisCN1w==
